on:
  workflow_dispatch:

jobs:
  check_resource_usage:
    permissions:
      # The "id-token: write" permission is required, or MWI will not be
      # able to authenticate with the cluster.
      id-token: write
      contents: read
    name: Check resource usage on server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Fetch Teleport binaries
        uses: teleport-actions/setup@v1
        with:
          proxy: mycluster.cloud.gravitational.io:443 # replace with your Teleport cluster address
          version: auto
      - name: Export ssh config
        run: tbot start --oneshot -c ./action_support/server_bot.yaml
      - name: Run mpstat
        # replace target server address with yours
        run: |
          ssh -F ./ssh_out/ssh_config ubuntu@myinstance.mycluster.cloud.gravitational.io mpstat