on:
  workflow_dispatch:

jobs:
  run_ssh_command:
    permissions:
      # The "id-token: write" permission is required, or MWI will not be
      # able to authenticate with the cluster.
      id-token: write
      contents: read
    name: Check resource usage on server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Fetch Teleport binaries
        uses: teleport-actions/setup@v1
        with:
          version: 18.1.5
      - name: Export ssh config
        run: tbot start --oneshot -c ./action_support/server_bot.yaml
      - name: Run mpstat
        run: |
          ssh -f ./ssh_out/ssh_config ubuntu@target1.my.cluster.com mpstat